### ISSUE TITLE
R.I.P.

### ISSUE THREAD

**Issue by Takehaniyasubiko** [danhans42/lite_menu#4]
Very sad to see Matt's empty threats killing this project. Today is a day when evil had won (yet again).

BTW, the only legitimate legal actions which can be taken in the case of PSIO is a class-action lawsuit against Cybdyn for false advertising.

EDIT: For those who don't know yet: https://github.com/danhans42/lite_menu/blob/main/images/danhans_sorry.pdf

**Comment by orabeidm** [comment]
Hmm.  Guy gave his word and then just threw everyone. Whether you're on vacation or not, you've shown yourself to be just like a pacifier without eggs. Regardless of what happens next and how this project develops, I stop following it. In my circles, they communicate only with those who does not throw words to the wind. As for the owners of clones, as well as those who have lost the keys to their official device, I invite you to our Russian forum 4pda.
You must register on the site and find the section "PSIO" on the forum. There are working patches with a removed blacklist. With hash validation disabled. It loads quickly, supports the latest known firmware version at the moment. There is also the latest firmware version that can be patched if you do not have a licensed version for the patch. It was found on one of the German retro gaming forums. Some person posted his in the public domain, probably he will be blacklisted. But on the other hand, everyone has the opportunity to use the software as conveniently. There is also, if anything, a telegram group in which new versions are posted.

https://4pda.to/forum/index.php?showtopic=1053197

![Screenshot_2023-08-14-21-34-47-791_ru.fourpda.client-edit.jpg](https://github.com/danhans42/lite_menu/assets/60073650/5192308b-bd8e-4f96-a5bb-2b9da31cbdbc)

**Comment by elgarlic** [comment]
The decision is completely understandable given the circumstances. I think the outcome emphasizes the need for taking extra precautions when dealing with these situations that can upset power-hungry dingbats. Warnings and advanced notice or previews for projects like these, as with fan-made games or movies of established IPs, will inevitably lead to their downfall. If the goal is to get something released, doing it swiftly and anonymously is really the only way to go when there are Matts and Nintendos in the world.

All the same, thanks for your efforts.

**Comment by orabeidm** [comment]
> The decision is completely understandable given the circumstances. I think the outcome emphasizes the need for taking extra precautions when dealing with these situations that can upset power-hungry dingbats. Warnings and advanced notice or previews for projects like these, as with fan-made games or movies of established IPs, will inevitably lead to their downfall. If the goal is to get something released, doing it swiftly and anonymously is really the only way to go when there are Matts and Nintendos in the world.
> 
> All the same, thanks for your efforts.

Hello! we are in Russia! we don't give a shit at all! besides, the guys are encrypted anyway. Do you think I'm so smart and did it all myself? I don't even know them. it's just that we have a strong closed community of fans of retro games and not ass-licking and liars.

**Comment by Takehaniyasubiko** [comment]
> The decision is completely understandable given the circumstances. I think the outcome emphasizes the need for taking extra precautions when dealing with these situations that can upset power-hungry dingbats. Warnings and advanced notice or previews for projects like these, as with fan-made games or movies of established IPs, will inevitably lead to their downfall. If the goal is to get something released, doing it swiftly and anonymously is really the only way to go when there are Matts and Nintendos in the world.
> 
> All the same, thanks for your efforts.

The difference between Matt and Nintendo is that Nintendo is for real, whereas Matt is a sole trader who DID NOT copyright the PSIO firmware (as he simply couldn't since it uses stolen Sony code), so he can't sue anybody over it. He already tried to scare the cloners and they just laughed him off. In fact, Matt could be sued for false advertising, but people are just to lazy to file a class-action lawsuit against him. Most of us are simply retro gamers who want to enjoy our hobby, not dabble in legal dramas because of some asshole who lies to the community.

**Comment by elgarlic** [comment]
> > The decision is completely understandable given the circumstances. I think the outcome emphasizes the need for taking extra precautions when dealing with these situations that can upset power-hungry dingbats. Warnings and advanced notice or previews for projects like these, as with fan-made games or movies of established IPs, will inevitably lead to their downfall. If the goal is to get something released, doing it swiftly and anonymously is really the only way to go when there are Matts and Nintendos in the world.
> > All the same, thanks for your efforts.
> 
> The difference between Matt and Nintendo is that Nintendo is for real, whereas Matt is a sole trader who DID NOT copyright the PSIO firmware (as he simply couldn't since it uses stolen Sony code), so he can't sue anybody over it. He already tried to scare the cloners and they just laughed him off. In fact, Matt could be sued for false advertising, but people are just to lazy to file a class-action lawsuit against him. Most of us are simply retro gamers who want to enjoy our hobby, not dabble in legal dramas because of some asshole who lies to the community.

Yeah, absolutely. It was still to be expected that Matt would attempt to strongarm the situation, though. If the primary goal was to get the menu released, it would have just been quietly released without hype. Matt could have attempted to have github take it down if he had a leg to stand on. And of course he would not. The idea that this situation would have inspired Matt to release an update by August 14th is silly. He has nothing to release.

**Comment by Takehaniyasubiko** [comment]
Matt has only one strategy: BLUFF.

He bluffed all those years ago by releasing PSIO with a broken firmware, and he's been bluffing ever since: about customer support, about firmware updates, about bushfires affecting his coding, about personal issues stopping him from working on PSIO, about cease and desist letters...

It's really obvious what he really wants: pre-order money for a product which doesn't truly do anything it is advertised to do.

**Comment by danhans42** [comment]
> Hmm. Guy gave his word and then just threw everyone. Whether you're on vacation or not, you've shown yourself to be just like a pacifier without eggs. Regardless of what happens next and how this project develops, I stop following it. In my circles, they communicate only with those who does not throw words to the wind. As for the owners of clones, as well as those who have lost the keys to their official device, I invite you to our Russian forum 4pda. You must register on the site and find the section "PSIO" on the forum. There are working patches with a removed blacklist. With hash validation disabled. It loads quickly, supports the latest known firmware version at the moment. There is also the latest firmware version that can be patched if you do not have a licensed version for the patch. It was found on one of the German retro gaming forums. Some person posted his in the public domain, probably he will be blacklisted. But on the other hand, everyone has the opportunity to use the software as conveniently. There is also, if anything, a telegram group in which new versions are posted.
> 
> https://4pda.to/forum/index.php?showtopic=1053197
> 
> ![Screenshot_2023-08-14-21-34-47-791_ru.fourpda.client-edit.jpg](https://user-images.githubusercontent.com/60073650/260541507-5192308b-bd8e-4f96-a5bb-2b9da31cbdbc.jpg)

Your comments made my holiday.

Fuckin hilarious. Have a good day 😘😘

**Comment by delon5** [comment]
He spoke a big game but when it came time to put up he shut up, classic lack of cahones.

**Comment by danhans42** [comment]
> He spoke a big game but when it came time to put up he shut up, classic lack of cahones.

Your partner said otherwise last night.
Get out the basement and touch grass. Life is too short

**Comment by danhans42** [comment]
> > The decision is completely understandable given the circumstances. I think the outcome emphasizes the need for taking extra precautions when dealing with these situations that can upset power-hungry dingbats. Warnings and advanced notice or previews for projects like these, as with fan-made games or movies of established IPs, will inevitably lead to their downfall. If the goal is to get something released, doing it swiftly and anonymously is really the only way to go when there are Matts and Nintendos in the world.
> > All the same, thanks for your efforts.
> 
> Hello! we are in Russia! we don't give a shit at all! besides, the guys are encrypted anyway. Do you think I'm so smart and did it all myself? I don't even know them. it's just that we have a strong closed community of fans of retro games and not ass-licking and liars.

No body owes you nothing.
Your nationality is irrelevant and doesn't define you, your own mentality does. 

There is more to life than battles and psio sunshine.
